[package]
name = "Assignment3_Q4"
version = "0.1.0"
authors = ["yilong"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
factorial = "0.2.0"
hamcrest2 = "0.3.0"


[dev-dependencies]
hamcrest2 = "*"