[package]
name = "Lab2_BinaryTree"
version = "0.1.0"
authors = ["yilong"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
